name: Rust Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    if: ${{ hashFiles('**/Cargo.toml') != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --all --all-targets
